#if DEBUG
using System.Collections.Generic;
using System.Reflection;
using HarmonyLib;
using MegaCrit.Sts2.Core.Hooks;
using RelicStats.Core;
using RelicStats.Core.Testing;

namespace RelicStats.Patches;

[HarmonyPatch(typeof(Hook), nameof(Hook.BeforeCombatStart))]
public static class TestCombatStartPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.CombatStart);
    }
}

[HarmonyPatch(typeof(Hook), nameof(Hook.AfterPlayerTurnStart))]
public static class TestPlayerTurnStartPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.PlayerTurnStart);
    }
}

[HarmonyPatch(typeof(Hook), nameof(Hook.AfterCombatVictory))]
public static class TestCombatVictoryPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.CombatVictory);
    }
}

[HarmonyPatch(typeof(Hook), nameof(Hook.AfterSideTurnStart))]
public static class TestSideTurnStartPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.SideTurnStart);
    }
}

[HarmonyPatch(typeof(Hook), nameof(Hook.AfterCombatEnd))]
public static class TestCombatEndPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.CombatEnd);
    }
}

// Renamed from BeforeTurnEnd/AfterTurnEnd to the SideTurn variants after 0.107.1.
[HarmonyPatch]
public static class TestTurnEndPatch
{
    public static IEnumerable<MethodBase> TargetMethods() =>
        PatchTarget.FirstDeclared(typeof(Hook), "BeforeSideTurnEnd", "BeforeTurnEnd");

    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.TurnEnd);
    }
}

[HarmonyPatch]
public static class TestAfterTurnEndPatch
{
    public static IEnumerable<MethodBase> TargetMethods() =>
        PatchTarget.FirstDeclared(typeof(Hook), "AfterSideTurnEnd", "AfterTurnEnd");

    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.AfterTurnEnd);
    }
}

// Priority.Last: the CardPlayed signal can run the next Assert synchronously, so it must come after
// every tracker postfix on Hook.AfterCardPlayed (SpikedGauntlets patches the same method).
[HarmonyPatch(typeof(Hook), nameof(Hook.AfterCardPlayed))]
[HarmonyPriority(Priority.Last)]
public static class TestCardPlayedPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.CardPlayed);
    }
}

[HarmonyPatch(typeof(Hook), nameof(Hook.AfterCardExhausted))]
public static class TestCardExhaustedPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.CardExhausted);
    }
}

[HarmonyPatch(typeof(Hook), nameof(Hook.AfterCardDiscarded))]
public static class TestCardDiscardedPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.CardDiscarded);
    }
}

[HarmonyPatch(typeof(Hook), nameof(Hook.AfterShuffle))]
public static class TestShufflePatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.Shuffle);
    }
}

[HarmonyPatch(typeof(Hook), nameof(Hook.AfterDamageReceived))]
public static class TestDamageReceivedPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.DamageReceived);
    }
}

[HarmonyPatch(typeof(Hook), nameof(Hook.AfterDeath))]
public static class TestDeathPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.Death);
    }
}

[HarmonyPatch(typeof(Hook), nameof(Hook.AfterGoldGained))]
public static class TestGoldGainedPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.GoldGained);
    }
}

[HarmonyPatch(typeof(Hook), nameof(Hook.AfterPotionUsed))]
public static class TestPotionUsedPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.PotionUsed);
    }
}

[HarmonyPatch(typeof(Hook), nameof(Hook.AfterRoomEntered))]
public static class TestRoomEnteredPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.RoomEntered);
    }
}

// Room-end rewards are generated by the combat UI roughly a second after AfterCombatVictory, so a
// reward relic asserted at CombatVictory always sees 0. ModifyRewards is the synchronous hook every
// reward relic (TryModifyRewards, and the card-reward hooks inside the same generation) has run by.
[HarmonyPatch(typeof(Hook), nameof(Hook.ModifyRewards))]
public static class TestRewardsGeneratedPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.RewardsGenerated);
    }
}

// A card added to the permanent deck reaches AfterCardChangedPiles only after an optional tween, so
// relics on that hook need a wait rather than an assert right after AddCardToDeck.
[HarmonyPatch(typeof(Hook), nameof(Hook.AfterCardChangedPiles))]
public static class TestCardChangedPilesPatch
{
    public static void Postfix()
    {
        TestManager.CheckTimeouts();
        TestManager.Signal(GameEvent.CardChangedPiles);
    }
}
#endif
